Add controllers
Sunkerus/java-shareit pull request #1
Opened 2023-05-23 15:02 UTC by Sunkerus

2023-05-24 14:31 UTC, alexache requested changes

2023-05-24 14:31 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Integer id;
Лучше везде полагаться на Long

2023-05-24 14:31 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +        }
а иначе?

2023-05-24 14:31 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/impl/ItemServiceImpl.java
> +    private final UserService userService;
Лучше сервису обращаться к стораджам, а не другим сервисам, чтобы не было лишний конвертаций из дто в модель и обратно

2023-05-24 14:31 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/User.java
> +    @Email(message = "Email not correct. Please enter correct email.")
Зачем валидации в модели?

2023-05-24 14:31 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    private String name;
А валидация имени?

2023-05-24 14:31 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/impl/UserServiceImpl.java
> +        boolean isExist = userStorage
Может и завести такой метод в сторадже existByEmail и подумать, как его сделать оптимальнее, чем просто обход всего списка пользователей?

2023-05-24 14:31 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/impl/UserStorageImpl.java
> +        return users.get(user.getId());
Зачем еще один гет?

2023-05-24 14:31 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/impl/ItemServiceImpl.java
> +            throw new NotFoundException("Item with that id coudn't found");
Может другое сообщение более подходящее?

2023-05-24 14:31 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/impl/ItemServiceImpl.java
> +        return itemStorage.getAll()
Тоже не очень изящно обходить весь список. Лучше у стораджа иметь такой  метод - получение вещей по владельцу, а внутри стораджа оптимизировать такой запрос использованием дополнительного словаря

2023-05-24 15:10 UTC, Sunkerus commented on src/main/java/ru/practicum/shareit/item/impl/ItemServiceImpl.java
> +    private final UserService userService;
Исправлено

2023-05-24 15:11 UTC, Sunkerus commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +        }
Исправил, добавил действие в случае else

2023-05-24 15:37 UTC, Sunkerus commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Integer owner;
Исправил

2023-05-24 15:40 UTC, Sunkerus commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    private String name;
Добавил валидацию

2023-05-24 16:03 UTC, Sunkerus commented on src/main/java/ru/practicum/shareit/user/impl/UserStorageImpl.java
> +        return users.get(user.getId());
Убрал лишний get, сделал один запрос, положил данные в переменную. повторный get выполняет функцию получения user из хранилища, после обновления.

2023-05-24 16:09 UTC, Sunkerus commented on src/main/java/ru/practicum/shareit/item/impl/ItemServiceImpl.java
> +            throw new NotFoundException("Item with that id coudn't found");
исправил

2023-05-24 16:45 UTC, Sunkerus commented on src/main/java/ru/practicum/shareit/item/impl/ItemServiceImpl.java
> +        if (userId == null) {
Исправил,  действительно сначала не подумал об этом

2023-05-24 17:39 UTC, Sunkerus commented on src/main/java/ru/practicum/shareit/user/impl/UserServiceImpl.java
> +        boolean isExist = userStorage
Добавил метод в userStorage

2023-05-24 17:48 UTC, Sunkerus commented on src/main/java/ru/practicum/shareit/user/impl/UserServiceImpl.java
> +        boolean isReplicatedEmail = userStorage.getAllUsers()
Исправил

2023-05-24 18:43 UTC, Sunkerus commented on src/main/java/ru/practicum/shareit/item/impl/ItemServiceImpl.java
> +        return itemStorage.getAll()
исправил

2023-05-24 18:54 UTC, Sunkerus commented on src/main/java/ru/practicum/shareit/item/impl/ItemServiceImpl.java
> +                .filter(item -> item.getName().toLowerCase().contains(text.toLowerCase())
исправил, вывел в отдельный метод

2023-05-25 13:27 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/impl/UserServiceImpl.java
> +                !opTest.orElseThrow(() -> new NotFoundException("User with email: " + userDto.getEmail() + "not found"))
Для чего это orElseThrow, если уже isPresent() стоит перед этим?

2023-05-26 05:14 UTC, Sunkerus commented on src/main/java/ru/practicum/shareit/user/impl/UserServiceImpl.java
> +                !opTest.orElseThrow(() -> new NotFoundException("User with email: " + userDto.getEmail() + "not found"))
Случайно добавил дополнительную проверку, сейчас исправил

2023-05-26 05:14 UTC, Sunkerus commented on src/main/java/ru/practicum/shareit/item/interfaces/ItemStorage.java
> +    Stream<Item> getAll();
Исправил

2023-05-26 05:28 UTC, merged