add: bookings
Sunkerus/java-shareit pull request #2
Opened 2023-05-28 16:29 UTC by Sunkerus

Выполнил задание согласно текущему тз, постарался написать грамотный код.

2023-05-28 21:04 UTC, alexache requested changes

2023-05-28 21:04 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +@Data
Повторный комментарий про эту аннотацию и модель

2023-05-28 21:04 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>  @Data
И здесь

2023-05-28 21:04 UTC, alexache commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
>  @Data
И здесь

2023-05-28 21:04 UTC, alexache commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
>  public class ItemRequestDto {
Почему этот класс пустой?

2023-05-28 21:04 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/User.java
>  @Data
И здесь

2023-05-28 23:34 UTC, Sunkerus commented on src/main/java/ru/practicum/shareit/booking/models/Booking.java
> +@Data
Выполнил замену на getter, setter и builder

2023-05-28 23:45 UTC, Sunkerus commented on src/main/java/ru/practicum/shareit/booking/models/Booking.java
> +@Data
Исправил

2023-05-29 00:39 UTC, Sunkerus commented on src/main/java/ru/practicum/shareit/user/User.java
>  @Data
Исправил

2023-05-29 00:43 UTC, Sunkerus commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
>  public class ItemRequestDto {
Исправил

2023-05-29 00:43 UTC, Sunkerus commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
>  @Data
Исправил

2023-05-29 00:43 UTC, Sunkerus commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>  @Data
Исправил

2023-05-29 00:43 UTC, Sunkerus commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +@Data
Исправил

2023-05-29 00:49 UTC, Sunkerus commented on src/main/java/ru/practicum/shareit/item/interfaces/ItemService.java
> +    Item getItemByIdAllField(Long id);
Оставил метод от ранее сделанного функционала.
Метод был без последующей реализации, удалил.

2023-05-29 01:00 UTC, Sunkerus commented on src/main/java/ru/practicum/shareit/item/impl/ItemServiceImpl.java
> +                .filter(u -> u.getStatus().name().equals("APPROVED"))
Исправил

2023-05-29 01:03 UTC, Sunkerus commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (Arrays.stream(BookingStatus.values()).anyMatch(status -> status.name().equals(state))) {
Мне этот вариант реализации показался наиболее рациональным т.к. всё, что мне удалось найти, предполагало наличие цикла или вспомогательных методов по типу EnumUtils.isValidEnum(MyEnum.class, myValue)

2023-05-29 01:32 UTC, Sunkerus commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (state == null || BookingPeriod.ALL.name().equals(state)) {
Не получилось заменить if на switch из - за необходимости константных переменных в switch

2023-05-29 07:35 UTC, alexache approved these changes

2023-05-29 07:35 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        boolean checkEnum = Arrays.stream(BookingStatus.values())
BookingStatus.valueOf(state)?

2023-05-29 07:35 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            case(FUTURE):
можно делать case и по просто строкам, case "FUTURE" -> ...

2023-05-29 07:35 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/impl/ItemServiceImpl.java
> +                .filter(u -> u.getStatus().name().equals("APPROVED"))
Я большк не про сам текст ошибки, а про 
        List<Booking> bookings = bookingStorage.findDistinctBookingByBookerIdAndItemId(bookerId, itemId); чтобы включить здесь и поиск по статусу APPROVED

2023-05-29 14:01 UTC, merged

2023-05-30 13:53 UTC, Sunkerus commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            case(FUTURE):
Исправил

2023-05-30 13:53 UTC, Sunkerus commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        boolean checkEnum = Arrays.stream(BookingStatus.values())
Исправил