refactor: slove problem with tests and other things
Sunkerus/java-shareit pull request #4
Opened 2023-05-31 14:59 UTC by Sunkerus

2023-06-01 13:28 UTC, alexache requested changes

2023-06-01 13:28 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/impl/ItemServiceImpl.java
> +    public Item getItemByIdAllField(Long id) {
Немного старый коммент - не нужно смешивать ДТО и модели в интерфейсе сервиса, Либо одно, либо другое

2023-06-01 13:28 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/mappers/ItemMapper.java
> +            listDtoOfItem.add(toDto(item));
(опционально) можно бы на стримах написать

2023-06-01 13:28 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +        assertEquals(bookingSufficiencyDto, mapper.readValue(result, BookingSufficiencyDto.class));
Хорошо бы еше в таких тестовых методах проверять количество вызовов мок сервиса через verify

2023-06-01 13:28 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +    private static User user;
А зачем эти поля статик?

2023-06-01 13:28 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/BookingStorageTest.java
> +    BookingStorage bookingStorage;
Модификаторы доступа полей не стоит убирать

2023-06-01 16:33 UTC, Sunkerus commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +    private static User user;
Исправил

2023-06-01 16:39 UTC, Sunkerus commented on src/test/java/ru/practicum/shareit/booking/BookingStorageTest.java
> +    BookingStorage bookingStorage;
Исправил

2023-06-01 16:39 UTC, Sunkerus commented on src/test/java/ru/practicum/shareit/booking/BookingStorageTest.java
> +    BookingStorage bookingStorage;
Исправил

2023-06-01 16:41 UTC, Sunkerus commented on src/main/java/ru/practicum/shareit/item/impl/ItemServiceImpl.java
> +    public Item getItemByIdAllField(Long id) {
Исправил

2023-06-01 16:48 UTC, Sunkerus commented on src/main/java/ru/practicum/shareit/item/mappers/ItemMapper.java
> +            listDtoOfItem.add(toDto(item));
Исправил

2023-06-01 17:07 UTC, Sunkerus commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +        assertEquals(bookingSufficiencyDto, mapper.readValue(result, BookingSufficiencyDto.class));
исправил

2023-06-03 15:49 UTC, alexache approved these changes

2023-06-05 06:48 UTC, merged