Add docker
Sunkerus/java-shareit pull request #6
Opened 2023-06-17 22:49 UTC by Sunkerus

2023-06-19 08:26 UTC, alexache requested changes

2023-06-19 08:26 UTC, alexache commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +        Map<String, Object> parameters = Map.of("approved", approved);
Можно обойтись без мапы из одного элемента

2023-06-19 08:26 UTC, alexache commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +    private void validateBooking(BookItemRequestDto requestDto) {
Это пусть лучше будет в контролере: а не клиенте

2023-06-19 08:26 UTC, alexache commented on server/pom.xml
> +            <groupId>jakarta.validation</groupId>
Не должно быть валидаций в сервисе: они все в гейтвее

2023-06-19 16:41 UTC, Sunkerus commented on server/pom.xml
> +            <groupId>jakarta.validation</groupId>
Исправил

2023-06-19 17:44 UTC, Sunkerus commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +    private void validateBooking(BookItemRequestDto requestDto) {
Исправил

2023-06-19 21:24 UTC, Sunkerus commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +    private void validateBooking(BookItemRequestDto requestDto) {
Исправил

2023-06-19 22:36 UTC, Sunkerus commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +        Map<String, Object> parameters = Map.of("approved", approved);
Исправил

2023-06-19 22:58 UTC, Sunkerus commented
Возникла проблема с прохождением локальных тестов, запускаемых гитом, не знаю , с чем это может быть связано, но в предыдущем коммите [2ec2a8d](https://github.com/Sunkerus/java-shareit/pull/6/commits/2ec2a8d7a4c5592b5b1e652bf64b45609571f6de), ты можешь посмотреть ,как выглядела изначальная версия. Локально тесты проходили без проблем, почему  - то после загрузки на гит, появилась такая проблема.

2023-06-20 18:00 UTC, alexache approved these changes

2023-06-20 18:06 UTC, merged